version: "3.1"
services:
    workspace:
        container_name: workspace
        build:
            context: ./phpdocker/workspace
            args:
                - INSTALL_YARN=${WORKSPACE_INSTALL_YARN}
                - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
                - INSTALL_WORKSPACE_SSH=${WORKSPACE_INSTALL_SSH}
                - NODE_VERSION=${WORKSPACE_NODE_VERSION}
                - TZ=${WORKSPACE_TIMEZONE}
                - PHP_VERSION=${PHP_VERSION}
        volumes:
            - ${APPLICATION}:/var/www
        ports:
            - "${WORKSPACE_SSH_PORT}:22"
        tty: true
        
    apache2:
        container_name: apache2
        build: 
            context: ./phpdocker/apache2
        working_dir: /var/www
        volumes:
            - ${APPLICATION}:/var/www
            - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
            - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
        ports:
            - "${APACHE_HOST_HTTP_PORT}:80"
            - "${APACHE_HOST_HTTPS_PORT}:443"
        links:
            - php-fpm    

    php-fpm:
        container_name: php-fpm
        build:
            context: ./phpdocker/php-fpm
            dockerfile: "Dockerfile-${PHP_VERSION}"
        working_dir: /var/www
        volumes:
            - ${APPLICATION}:/var/www
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        links:
            - mysql
            
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"

#    composer:
#        restart: 'no'
#        image: composer/composer:php7
#        command: install
#        working_dir: /var/www
#        volumes:
#            - ${APPLICATION}:/var/www